Css ecommerce page - Nick Newton
NickANewton/c0322-code-solutions pull request #33
Opened 2022-03-23 20:53 UTC by NickANewton

![Screen Shot 2022-03-23 at 1 48 31 PM](https://user-images.githubusercontent.com/99566488/159793621-9d039c3a-b69c-4377-a56d-779ba852a35d.png)

2022-03-24 18:58 UTC, codingcodymiller requested changes

2022-03-24 18:58 UTC, codingcodymiller commented on css-ecommerce-page/index.html
> +        </div>
Instead of making this a `div` element with `p` child elements, I would make this a `p` element with `span` child elements

2022-03-25 05:21 UTC, NickANewton commented
![Screen Shot 2022-03-23 at 1 48 31 PM](https://user-images.githubusercontent.com/99566488/160059489-70caca2e-2bff-4940-9c1b-51f2a69a4b07.png)

2022-03-25 05:21 UTC, NickANewton commented
![Screen Shot 2022-03-24 at 10 20 39 PM](https://user-images.githubusercontent.com/99566488/160059542-a75ea386-d52a-438d-aa2f-059b395bd550.png)

2022-03-25 18:07 UTC, merged