completed string-manipulation-1 exercise - Nick Newton
NickANewton/c0322-code-solutions pull request #37
Opened 2022-03-25 20:06 UTC by NickANewton

![StringMan1](https://user-images.githubusercontent.com/99566488/160193577-bbefdbed-2ded-4071-95b0-6ab67e9ba356.gif)

2022-03-25 22:41 UTC, codingcodymiller requested changes

2022-03-25 22:41 UTC, codingcodymiller commented on string-manipulation-1/src/is-vowel.js
> +  for (var i = 0; i < 5; i++) {
If somebody decides that `"y` should be one of the vowels, this loop would end up breaking 😬

2022-03-25 23:32 UTC, NickANewton commented
![StringMan1_2](https://user-images.githubusercontent.com/99566488/160214563-5c0976b2-69d9-43c0-8c9a-150a90296c7c.gif)

2022-03-26 00:13 UTC, codingcodymiller approved these changes
Nice work!!

2022-03-26 00:34 UTC, merged